[package]
name = "rwc"
version = "0.1.0"
authors = ["Adam P. Regasz-Rethy <adam.regaszrethy@gmail.com>"]
edition = "2018"

[dependencies]
structopt = "0.3"
walkdir = "2"
utf-8 = "0.7.5"
colored = "2"
term-table = "1.3.1"
num-format = "0.4.0"
bytecount = "0.6.2"
rayon = "1.5"
